services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./.docker-compose/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  redis:
    container_name: redis_motorway
    image: redis
    restart: always
    ports:
      - 6379:6379
