services:
  postgres:
    container_name: postgres_jelly
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: jelly
  redis:
    container_name: redis_jelly
    image: redis
    restart: always
    ports:
      - 6379:6379
  rabbitmq:
      container_name: rmq_jelly
      image: rabbitmq:3-management
      hostname: rabbitmq-jelly
      environment:
        RABBITMQ_DEFAULT_USER: "admin"
        RABBITMQ_DEFAULT_PASS: "admin"
        RABBITMQ_ERLANG_COOKIE: "admin"
      ports:
        - 5673:5672 # AMQP protocol
        - 15672:15672 # Management UI
      volumes:
        - ".rmq:/var/lib/rabbitmq"
      restart: always