global:
  scrape_interval: 5s # Adjust based on your needs

scrape_configs:
  - job_name: 'fastify_local'
    static_configs:
      - targets: ['host.docker.internal:3000'] # Needed for Docker to access localhost
